<?php

namespace AppBundle\Repository;

/**
 * TpWebserviceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TpWebserviceRepository extends \Doctrine\ORM\EntityRepository
{
}
