
convert:
    path:     /convertir
    defaults: { _controller: AppBundle:Convertisseur:convert }

convert_new:
    path:     /convertir/{From}-{To}/{Amount}
    defaults: { _controller: AppBundle:Convertisseur:convert }

save:
    path:     /save/{From}-{To}/{Amount}
    defaults: { _controller: AppBundle:Convertisseur:save }

update:
    path:     /update-convertions/
    defaults: { _controller: AppBundle:Convertisseur:update }

index:
    path:     /
    defaults: { _controller: AppBundle:Convertisseur:index }

app_tpwebservice:
    resource: "@AppBundle/Resources/config/routing/tpwebservice.yml"
    prefix:   /tpwebservice